#pragma once


#include "UObject/ObjectMacros.h"
#include "UObject/Object.h"
#include "Containers/Union.h"
#include "Runtime/Json/Public/Json.h"
#include "Serialization/JsonSerializerMacros.h"
#include "Runtime/Core/Public/Async/Future.h"


#include "Common/SSGS_JsonConvertable.h"
#include "Common/SSGS_Union.h"

#include "Types/SSGS_DeviceZone.h"
#include "Types/SSGS_Enums.h"
#include "Types/Rate/SSGS_Frequency.h"
#include "Types/Rate/SSGS_RepeatLimit.h"
#include "Types/Rate/SSGS_FrequencyRepeatLimitPair.h"
#include "Types/Rate/SSGS_RateStatic.h"
#include "Types/Rate/SSGS_RateRange.h"
#include "Types/Rate/SSGS_RateSpecification.h"
#include "Types/Illumination/SSGS_RGB.h"
#include "Types/Illumination/SSGS_Gradient.h"
#include "Types/Illumination/SSGS_ColorGradient.h"
#include "Types/Illumination/SSGS_ColorRangeStatic.h"
#include "Types/Illumination/SSGS_ColorRangeGradient.h"
#include "Types/Illumination/SSGS_ColorRange.h"
#include "Types/Illumination/SSGS_ColorEffectSpecification.h"
#include "Types/Illumination/SSGS_ColorEffectSpecificationStatic.h"
#include "Types/Illumination/SSGS_ColorEffectSpecificationGradient.h"
#include "Types/Illumination/SSGS_ColorEffectSpecificationRanges.h"
#include "Types/Haptics/SSGS_PredefinedTactilePatterns.h"
#include "Types/Haptics/SSGS_TactileEffectPredefined.h"
#include "Types/Haptics/SSGS_TactileEffectCustom.h"
#include "Types/Haptics/SSGS_TactilePatternStatic.h"
#include "Types/Haptics/SSGS_TactilePatternRange.h"
#include "Types/Haptics/SSGS_TactilePatternSpecification.h"
#include "Types/Haptics/SSGS_TactilePatternSpecificationStatic.h"
#include "Types/Haptics/SSGS_TactilePatternSpecificationRanges.h"
#include "Types/Handler/SSGS_HandlerColor.h"
#include "Types/Handler/SSGS_HandlerTactile.h"
#include "Types/Handler/SSGS_HandlerCollection.h"
#include "Types/SSGS_EventData.h"
#include "Types/SSGS_Payload.h"
